"""create_core_schema

Revision ID: 78acc450651d
Revises: 001
Create Date: 2026-06-17 17:23:46.232690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78acc450651d'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parking_sites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('timezone', sa.String(length=100), server_default='Asia/Ho_Chi_Minh', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('vehicle_owners',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_code', sa.String(length=100), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('owner_type', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('identity_number', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('avatar_media_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_code')
    )
    op.create_table('vehicle_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_fee_rule_id', sa.UUID(), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('fee_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('vehicle_type_id', sa.UUID(), nullable=True),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('priority', sa.Integer(), server_default='10', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_type_id'], ['vehicle_types.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('parking_zones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('capacity', sa.Integer(), server_default='0', nullable=False),
    sa.Column('current_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('vehicle_type_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['parking_sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'code', name='uq_parking_zones_site_code')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('vehicle_type_id', sa.UUID(), nullable=False),
    sa.Column('plate_number', sa.String(length=50), nullable=True),
    sa.Column('normalized_plate_number', sa.String(length=50), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_media_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['vehicle_owners.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_type_id'], ['vehicle_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bucket', sa.String(length=255), nullable=False),
    sa.Column('object_key', sa.Text(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('checksum', sa.String(length=255), nullable=True),
    sa.Column('media_type', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parking_gates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('gate_type', sa.String(length=50), nullable=False),
    sa.Column('direction', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['parking_zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zone_id', 'code', name='uq_parking_gates_zone_code')
    )
    op.create_table('rfid_cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('card_uid', sa.String(length=255), nullable=False),
    sa.Column('card_number', sa.String(length=255), nullable=True),
    sa.Column('card_type', sa.String(length=50), server_default='rfid', nullable=False),
    sa.Column('assigned_vehicle_id', sa.UUID(), nullable=True),
    sa.Column('assigned_owner_id', sa.UUID(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='active', nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_owner_id'], ['vehicle_owners.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_uid')
    )
    op.create_table('cameras',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gate_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('camera_type', sa.String(length=50), nullable=False),
    sa.Column('stream_url', sa.Text(), nullable=True),
    sa.Column('snapshot_url', sa.Text(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password_secret_key', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='offline', nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('agent_id', sa.String(length=255), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gate_id'], ['parking_gates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gate_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('device_type', sa.String(length=50), nullable=False),
    sa.Column('connection_type', sa.String(length=50), nullable=False),
    sa.Column('connection_config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('status', sa.String(length=50), server_default='offline', nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('firmware_version', sa.String(length=100), nullable=True),
    sa.Column('agent_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gate_id'], ['parking_gates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('parking_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_code', sa.String(length=100), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('gate_entry_id', sa.UUID(), nullable=False),
    sa.Column('gate_exit_id', sa.UUID(), nullable=True),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('vehicle_type_id', sa.UUID(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('entry_card_id', sa.UUID(), nullable=True),
    sa.Column('exit_card_id', sa.UUID(), nullable=True),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('entry_plate_number', sa.String(length=50), nullable=True),
    sa.Column('exit_plate_number', sa.String(length=50), nullable=True),
    sa.Column('entry_plate_confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('exit_plate_confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('entry_overview_image_id', sa.UUID(), nullable=True),
    sa.Column('entry_plate_image_id', sa.UUID(), nullable=True),
    sa.Column('exit_overview_image_id', sa.UUID(), nullable=True),
    sa.Column('exit_plate_image_id', sa.UUID(), nullable=True),
    sa.Column('entry_user_id', sa.UUID(), nullable=True),
    sa.Column('exit_user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='active', nullable=False),
    sa.Column('fee_rule_id', sa.UUID(), nullable=True),
    sa.Column('calculated_fee', sa.Numeric(precision=18, scale=2), server_default='0.0', nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=18, scale=2), server_default='0.0', nullable=False),
    sa.Column('payment_status', sa.String(length=50), server_default='unpaid', nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('warning_flags', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entry_card_id'], ['rfid_cards.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['entry_overview_image_id'], ['media_files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['entry_plate_image_id'], ['media_files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['entry_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['exit_card_id'], ['rfid_cards.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['exit_overview_image_id'], ['media_files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['exit_plate_image_id'], ['media_files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['exit_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fee_rule_id'], ['fee_rules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['gate_entry_id'], ['parking_gates.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['gate_exit_id'], ['parking_gates.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['vehicle_owners.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['parking_sites.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_type_id'], ['vehicle_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['zone_id'], ['parking_zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_code')
    )
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parking_session_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('payment_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reference_code', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parking_session_id'], ['parking_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('roles', 'permissions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.drop_constraint(op.f('users_role_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_role_id_fkey'), 'users', 'roles', ['role_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('roles', 'permissions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.drop_table('payments')
    op.drop_table('parking_sessions')
    op.drop_table('devices')
    op.drop_table('cameras')
    op.drop_table('rfid_cards')
    op.drop_table('parking_gates')
    op.drop_table('media_files')
    op.drop_table('vehicles')
    op.drop_table('parking_zones')
    op.drop_table('fee_rules')
    op.drop_table('vehicle_types')
    op.drop_table('vehicle_owners')
    op.drop_table('parking_sites')
    # ### end Alembic commands ###
